name: ChallengePlugin
version: '${project.version}'
main: io.github.rysefoxx.challenge.core.ChallengePlugin
authors: [ Rysefoxx ]
description: ChallengePlugin Plugin
api-version: 1.19
libraries:
  - net.kyori:adventure-text-minimessage:4.12.0
  - net.kyori:adventure-platform-bukkit:4.2.0
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7
commands:
  settings: